Repository team-haribo/GOMS-Backend, pull requests merged in 2023-07, with the labels that each got.

#25 🔀 :: BaseIdxEntity, BaseUUIDEntity 생성
  src/main/kotlin/com/project/goms/domain/account/entity/Account.kt
  src/main/kotlin/com/project/goms/domain/late/entity/Late.kt
  src/main/kotlin/com/project/goms/domain/outing/entity/Outing.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/entity/StudentCouncil.kt
  src/main/kotlin/com/project/goms/global/entity/BaseIdxEntity.kt
  src/main/kotlin/com/project/goms/global/entity/BaseUUIDEntity.kt
Labels: 0️⃣ Priority: Critical, 😈 버그 fix

#27 🔀 :: 404 반환하기
  src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt
  src/main/kotlin/com/project/goms/global/security/handler/CustomAccessDeniedHandler.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#28 🔀 :: 외출중인 학생 검색하기
  src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/StudentCouncilConverter.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/impl/StudentCouncilConverterImpl.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/data/response/SearchOutingResponse.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/SearchOutingUseCase.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/dto/SearchOutingDto.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#32 🔀 :: 현재 외출중인 학생을 검색할 수 있는 권한을 학생에게도 부여
  src/main/kotlin/com/project/goms/domain/outing/common/util/OutingConverter.kt
  src/main/kotlin/com/project/goms/domain/outing/common/util/impl/OutingConverterImpl.kt
  src/main/kotlin/com/project/goms/domain/outing/presentation/OutingController.kt
  src/main/kotlin/com/project/goms/domain/outing/presentation/data/response/SearchOutingResponse.kt
  src/main/kotlin/com/project/goms/domain/outing/usecase/SearchOutingUseCase.kt
  src/main/kotlin/com/project/goms/domain/outing/usecase/dto/SearchOutingDto.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/StudentCouncilConverter.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/common/util/impl/StudentCouncilConverterImpl.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
  src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#34 🔀 :: 토큰 재발급 받을때 기존의 RefreshToken 삭제
  src/main/kotlin/com/project/goms/domain/auth/usecase/ReissueTokenUseCase.kt
  src/test/kotlin/com/project/goms/domain/auth/ReissueTokenUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#41 🔀 :: CreatedTime LocalDateTime -> String으로 타입 변환
  src/main/kotlin/com/project/goms/domain/outing/common/util/impl/OutingConverterImpl.kt
  src/main/kotlin/com/project/goms/domain/outing/presentation/data/response/OutingAccountResponse.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#38 🔀 :: 외출 가능 시간인지 확인하는 기능추가
  src/main/kotlin/com/project/goms/domain/outing/presentation/OutingController.kt
  src/main/kotlin/com/project/goms/domain/outing/usecase/ValidateOutingTimeUseCase.kt
  src/main/kotlin/com/project/goms/global/annotation/UseCase.kt
  src/main/kotlin/com/project/goms/global/config/ComponentScanConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#44 🔀 :: 외출 학생 null이면 전체 학생 반환하기
  src/main/kotlin/com/project/goms/domain/outing/common/util/impl/OutingConverterImpl.kt
  src/main/kotlin/com/project/goms/domain/outing/presentation/OutingController.kt
  src/main/kotlin/com/project/goms/domain/outing/usecase/SearchOutingUseCase.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#46 🔀 :: 외출 가능한지 반환할때 객체에 담아서 반환하기
  src/main/kotlin/com/project/goms/domain/outing/common/util/impl/OutingConverterImpl.kt
  src/main/kotlin/com/project/goms/domain/outing/presentation/OutingController.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#48 🔀 :: 외출 안되는 이슈 해결
  src/main/kotlin/com/project/goms/domain/outing/entity/Outing.kt
Labels: 0️⃣ Priority: Critical, 😈 버그 fix

#50 🔀 :: 현재 외출중인 학생 검색하기 테스트 코드 추가
  src/test/kotlin/com/project/goms/domain/outing/SearchOutingUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#52 🔀 :: 외출자 삭제 테스트 코드 추가
  src/test/kotlin/com/project/goms/domain/studentCouncil/DeleteOutingUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#54 🔀 :: OutingRepository 타입 변경
  src/main/kotlin/com/project/goms/domain/outing/entity/repository/OutingRepository.kt
Labels: 3️⃣ Priority: Low, 🔨 코드 리팩터링

#56 🔀:: 현재 외출 가능한 시간인지 구분하는 기능 테스트 코드 작성
  src/test/kotlin/com/project/goms/domain/outing/ValidateOutingTimeUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test
