Repository team-haribo/GOMS-Backend, pull requests merged in 2023-06, with the labels that each got.

#3 🔀 :: pr template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2️⃣ Priority: Medium, 📃 Docs

#6 :fire: @Indexed 어노테이션 삭제
  src/main/kotlin/com/project/goms/domain/outing/entity/OutingBlackList.kt
Labels: 3️⃣ Priority: Low, 🔨 코드 리팩터링

#10 🔀 :: main에 push 될때만 CD 실행
  .github/workflows/CD.yml
Labels: 1️⃣ Priority: High

#11 🔀 :: AccountDto 삭제하기
  src/main/kotlin/com/project/goms/domain/account/usecase/dto/AccountDto.kt
Labels: 3️⃣ Priority: Low, 🔨 코드 리팩터링

#12 🔀 :: 외출 디스코드 스케줄러 시간 설정
  src/main/kotlin/com/project/goms/domain/outing/scheduler/OutingScheduler.kt
Labels: 2️⃣ Priority: Medium

#14 🔀 :: 디스코드 스케줄러 수정
  src/main/kotlin/com/project/goms/domain/outing/scheduler/OutingScheduler.kt
Labels: 2️⃣ Priority: Medium, 😈 버그 fix

#18 🔀 :: 외출자 삭제 로직 잘못된 부분 수정
  src/main/kotlin/com/project/goms/domain/studentCouncil/presentation/StudentCouncilController.kt
  src/main/kotlin/com/project/goms/domain/studentCouncil/usecase/DeleteOutingUseCase.kt
  src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium
