Repository team-haribo/GOMS-Backend, pull requests merged in 2023-09, with the labels that each got.

#64 🔀 :: 개발 서버 CD 스크립트 추가
  .github/workflows/CD-Dev.yml
  .github/workflows/CD-Prod.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#63 🔀 :: FCM 알림 기능 추가
  build.gradle.kts
  src/main/kotlin/com/project/goms/domain/notification/common/exception/DeviceTokenNotFoundException.kt
  src/main/kotlin/com/project/goms/domain/notification/entity/DeviceToken.kt
  src/main/kotlin/com/project/goms/domain/notification/entity/Notification.kt
  src/main/kotlin/com/project/goms/domain/notification/entity/NotificationType.kt
  src/main/kotlin/com/project/goms/domain/notification/entity/Topic.kt
  src/main/kotlin/com/project/goms/domain/notification/entity/Writer.kt
  src/main/kotlin/com/project/goms/domain/notification/entity/repository/DeviceTokenRepository.kt
  src/main/kotlin/com/project/goms/domain/notification/presentation/NotificationController.kt
  src/main/kotlin/com/project/goms/domain/notification/scheduler/NotificationScheduler.kt
  src/main/kotlin/com/project/goms/domain/notification/spi/NotificationPort.kt
  src/main/kotlin/com/project/goms/domain/notification/usecase/SendNotificationUseCase.kt
  src/main/kotlin/com/project/goms/domain/notification/usecase/SetDeviceTokenUseCase.kt
  src/main/kotlin/com/project/goms/domain/outing/scheduler/OutingScheduler.kt
  src/main/kotlin/com/project/goms/domain/outing/usecase/ReminderOutingUseCase.kt
  src/main/kotlin/com/project/goms/domain/outing/usecase/SendMessageUseCase.kt
  src/main/kotlin/com/project/goms/global/config/PropertiesScanConfig.kt
  src/main/kotlin/com/project/goms/global/error/ErrorCode.kt
  src/main/kotlin/com/project/goms/infrastructure/.gitkeep
  src/main/kotlin/com/project/goms/infrastructure/discord/usecase/SendDiscordUseCase.kt
  src/main/kotlin/com/project/goms/infrastructure/discord/usecase/dto/DiscordDto.kt
  src/main/kotlin/com/project/goms/infrastructure/feign/client/DiscordFeignClient.kt
  src/main/kotlin/com/project/goms/infrastructure/feign/config/FeignConfig.kt
  src/main/kotlin/com/project/goms/infrastructure/feign/error/FeignClientErrorDecoder.kt
  src/main/kotlin/com/project/goms/infrastructure/feign/error/exception/FeignBadRequestException.kt
  src/main/kotlin/com/project/goms/infrastructure/feign/error/exception/FeignForbiddenException.kt
  src/main/kotlin/com/project/goms/infrastructure/feign/error/exception/FeignUnAuthorizedException.kt
  src/main/kotlin/com/project/goms/infrastructure/notification/FcmAdapter.kt
  src/main/kotlin/com/project/goms/infrastructure/notification/config/FcmConfig.kt
  src/main/kotlin/com/project/goms/infrastructure/notification/property/FcmProperties.kt
  src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#66 🔀 :: mariaDB 의존성 추가
  build.gradle.kts
Labels: 2️⃣ Priority: Medium

#68 🔀 :: 지각자 저장 시간 저장
  src/main/kotlin/com/project/goms/domain/outing/scheduler/OutingScheduler.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#70 🔀 :: LocalDateTime 패턴 v2랑 같게 변경
  src/main/kotlin/com/project/goms/domain/auth/presentation/data/response/TokenResponse.kt
Labels: 2️⃣ Priority: Medium

#72 🔀 :: notification api 권한 추가
  src/main/kotlin/com/project/goms/domain/notification/entity/DeviceToken.kt
  src/main/kotlin/com/project/goms/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium
